#ifndef _AST_ENUM_
#define _AST_ENUM_

enum class ASTNodeType : int {
    PROGRAM,
    FUNCTION_DEFINITION,
    FUNCTION_NAME,
    PARAM_LIST,
    BLOCK,
    VAR_DEFINITION,
    VAR_TYPE,
    VAR_NAME,
    ASSIGNMENT_EXPRESSION,
    INT_LITERAL,
    FLOAT_LITERAL,
    STRING_LITERAL,
    BOOLEAN_LITERAL,
    FUNCTION_CALL,
    ARGUMENT_LIST,
    EXPRESSION,
    OPERATOR,
    RETURN_STATEMENT,
    RETURN_LIST,
    RETURN_TYPE,
    IF_STATEMENT,
    WHILE_STATEMENT,
    BREAK,
    CONTINUE,
};

#endif